definitions:
  ProductList:
    type: array
    items:
      $ref: '#/definitions/Product'
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: Unique ID.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
