swagger: '2.0'
info:
  title: example
  description: swagger-bundler examples
  version: 1.0.0
host: localhost
schemes:
- http
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
definitions:
  ZZZProductList:
    type: array
    items:
      $ref: '#/definitions/ZZZProduct'
  ZZZProduct:
    type: object
    properties:
      product_id:
        type: string
        description: Unique ID.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
  ZZZSeriesList:
    type: array
    items:
      $ref: '#/definitions/ZZZSeries'
  ZZZSeries:
    type: object
    properties:
      series_id:
        type: string
        description: Unique ID.
      display_name:
        type: string
        description: Display name of series.
      products:
        type: array
        items:
          $ref: '#/definitions/ZZZProduct'
        description: Display name of series.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
responses:
  UnexpectedError:
    description: Unexpected error
    schema:
      $ref: '#/definitions/Error'
paths:
  /products:
    get:
      summary: Product Types
      description: <description>
      responses:
        200:
          description: An array of products
          schema:
            $ref: '#/definitions/ZZZProductList'
        default:
          $ref: '#/responses/UnexpectedError'
  /seriess:
    get:
      summary: Series Types
      description: <description>
      responses:
        200:
          description: An array of seriess
          schema:
            $ref: '#/definitions/ZZZSeriesList'
        default:
          $ref: '#/responses/UnexpectedError'
